prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:  <http://www.w3.org/2002/07/owl#>

select distinct ?term
where {
  {?term a rdf:Property}         union
  {?term a owl:DatatypeProperty} union 
  {?term a owl:ObjectProperty}   union
  {?term a owl:Class}            union 
  {?term a rdfs:Class}
  filter(regex(str(?term),'http://www.w3.org/ns/prov#'))
}
order by ?term
